---
new_page_extension: md
auto_deploy: true
admin_path: forestry
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: bubblor
  label: Bubblor
  create: all
  match: "**/*"
  hidden: true
- type: directory
  path: skolwebb
  label: Skolwebb
  create: all
  match: "**/*"
  hidden: true
- type: directory
  path: hand
  label: Hand
  create: all
  match: "**/*"
  hidden: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
